version: '3.8'

services:
  customer-postgres:
    container_name: customer_postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: customer
      PGDATA: /data/postgres
    volumes:
      - customer_postgres_data:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - app_network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - app_network
    restart: unless-stopped

  fraud-mongodb:
    container_name: fraud-mongodb
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: fraud_db
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - app_network
    restart: unless-stopped

  notification-postgres:
    container_name: notification_postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: notification
      PGDATA: /data/postgres
    volumes:
      -  notification_postgres_data:/data/postgres
    ports:
      - "5455:5432"
    networks:
      - app_network
    restart: unless-stopped

volumes:
  customer_postgres_data:
  pgadmin:
  mongodb:
  notification_postgres_data:
  #mysql:

networks:
  app_network:
    driver: bridge