server:
  port: 8083

spring:
  application:
    name: notification
  datasource:
    url: jdbc:postgresql://localhost:5455/notification
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

application:
  title: FINOVAEDGE
  version: 1.0.0
  author: Yassine CHALH

